apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-assisted-devops
  labels:
    app: ai-assisted-devops

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ai-assisted-devops

  template:
    metadata:
      labels:
        app: ai-assisted-devops

    spec:
      containers:
        - name: ai-assisted-devops
          image: ai-assisted-devops-platform:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000  